# Generated by Django 5.0.6 on 2024-06-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('paid', 'Paid'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
