# Generated by Django 5.0.6 on 2024-06-14 07:47

import django.utils.timezone
import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pizza', 'Pizza'), ('sandwich', 'Sandwich'), ('pasta', 'Pasta'), ('burger', 'Burger'), ('salad', 'Salad'), ('drink', 'Drink'), ('other', 'Other')], max_length=30)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant_app.models.food_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_hours', models.JSONField(default=restaurant_app.models.default_opening_hours)),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant_app.models.restaurant_image_path)),
                ('documents', models.FileField(blank=True, null=True, upload_to=restaurant_app.models.restaurant_document_path)),
            ],
        ),
    ]
